export const lista_origen = [
  { origen_id: "", origen_nombre: "-", lista_beneficios: null },
  {
    origen_id: 1,
    origen_nombre: "ENTEL TOTAL 19.90",
    lista_beneficios: [
      "2 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 2,
    origen_nombre: "ENTEL CHIP 20.90 REV",
    lista_beneficios: [
      "4 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 3,
    origen_nombre: "ENTEL CHIP 20.90 PLUS",
    lista_beneficios: [
      "4 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 4,
    origen_nombre: "ENTEL CHIP 25.90 REV",
    lista_beneficios: [
      "6 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 5,
    origen_nombre: "ENTEL CHIP 25.90",
    lista_beneficios: [
      "6 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 6,
    origen_nombre: "ENTEL CHIP+ 29.90 REV",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 7,
    origen_nombre: "ENTEL SIMPLE+ 29.90",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 8,
    origen_nombre: "ENTEL CHIP+ 29.90",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 9,
    origen_nombre: "ENTEL CHIP 30.90 REV",
    lista_beneficios: [
      "11 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 10,
    origen_nombre: "POSTPAGO SIMPLE 30.90",
    lista_beneficios: [
      "11 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 11,
    origen_nombre: "ENTEL CHIP 30.90 B",
    lista_beneficios: [
      "11 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 12,
    origen_nombre: "ENTEL CHIP 30.90",
    lista_beneficios: [
      "11 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 13,
    origen_nombre: "POSTPAGO SIMPLE 32.90 PLUS",
    lista_beneficios: [
      "15 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 14,
    origen_nombre: "ENTEL CHIP 32.90",
    lista_beneficios: [
      "15 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 15,
    origen_nombre: "ENTEL CHIP 37.90 PLUS",
    lista_beneficios: [
      "20 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 16,
    origen_nombre: "ENTEL SIMPLE+ 39.90",
    lista_beneficios: [
      "25 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 17,
    origen_nombre: "ENTEL CHIP+ 39.90",
    lista_beneficios: [
      "25 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 18,
    origen_nombre: "NEGOCIO CHIP R 41.90",
    lista_beneficios: ["13 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 19,
    origen_nombre: "ENTEL CHIP 43.50 REV",
    lista_beneficios: [
      "28 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 20,
    origen_nombre: "POSTPAGO SIMPLE 43.50 PLUS",
    lista_beneficios: [
      "28 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 21,
    origen_nombre: "ENTEL CHIP 43.50 PLUS",
    lista_beneficios: [
      "28 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 22,
    origen_nombre: "ENTEL CHIP 45.90 PLUS",
    lista_beneficios: [
      "30 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 23,
    origen_nombre: "ENTEL CHIP 48.90 PLUS",
    lista_beneficios: [
      "32 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 24,
    origen_nombre: "ENTEL POWER+ 49.90",
    lista_beneficios: [
      "35 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 25,
    origen_nombre: "ENTEL CHIP 49.90 PLUS B",
    lista_beneficios: [
      "35 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 26,
    origen_nombre: "ENTEL CHIP 49.90 PLUS A",
    lista_beneficios: [
      "14 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 27,
    origen_nombre: "ENTEL CONTROL 49.90 PLUS",
    lista_beneficios: [
      "14 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 28,
    origen_nombre: "ENTEL POWER 49.90",
    lista_beneficios: ["Ilimitado con 9 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 29,
    origen_nombre: "ENTEL CHIP 49.90 PLUS",
    lista_beneficios: [
      "35 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 30,
    origen_nombre: "ENTEL POWER+ 55.90",
    lista_beneficios: [
      "50 GB en AV",
      "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
      "Roaming: 2.5 GB",
    ],
  },
  {
    origen_id: 31,
    origen_nombre: "ENTEL CHIP 55.90 PLUS",
    lista_beneficios: [
      "50 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 32,
    origen_nombre: "ENTEL CHIP 55.90 PLUS B",
    lista_beneficios: [
      "50 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 33,
    origen_nombre: "ENTEL POWER+ 59.90",
    lista_beneficios: [
      "75 GB en AV",
      "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
      "Roaming: 3 GB",
    ],
  },
  {
    origen_id: 34,
    origen_nombre: "ENTEL POWER 59.90",
    lista_beneficios: ["Ilimitado con 50 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 35,
    origen_nombre: "ENTEL CHIP 65.90 PLUS B",
    lista_beneficios: [
      "85 GB en AV",
      "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 36,
    origen_nombre: "ENTEL CHIP 65.90 PLUS",
    lista_beneficios: [
      "85 GB en AV",
      "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 37,
    origen_nombre: "ENTEL POWER 65.90 P",
    lista_beneficios: ["Ilimitado con 16 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 38,
    origen_nombre: "ENTEL POWER 65.90 A",
    lista_beneficios: ["Ilimitado con 16 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 39,
    origen_nombre: "ENTEL POWER 65.90 H",
    lista_beneficios: ["Ilimitado con 16 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 40,
    origen_nombre: "NEGOCIO CHIP R 65.90",
    lista_beneficios: ["18 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 41,
    origen_nombre: "ENTEL POWER 69.90 A",
    lista_beneficios: ["Ilimitado con 26 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 42,
    origen_nombre: "ENTEL POWER+ 74.90",
    lista_beneficios: [
      "120 GB en AV",
      "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
      "Roaming: 3.5 GB",
    ],
  },
  {
    origen_id: 43,
    origen_nombre: "ENTEL CHIP 74.90 PLUS",
    lista_beneficios: [
      "100 GB en AV",
      "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 44,
    origen_nombre: "ENTEL POWER 74.90 B",
    lista_beneficios: ["Ilimitado con 100 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 45,
    origen_nombre: "ENTEL POWER 74.90",
    lista_beneficios: ["100 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 46,
    origen_nombre: "NEGOCIO CHIP R 84.80",
    lista_beneficios: ["25 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 47,
    origen_nombre: "ENTEL CHIP 84.90",
    lista_beneficios: [
      "110 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 48,
    origen_nombre: "ENTEL CONTROL 84.90",
    lista_beneficios: [
      "9 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 49,
    origen_nombre: "ENTEL POWER 89.90 SD",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
  },
  {
    origen_id: 50,
    origen_nombre: "ENTEL CHIP 89.90",
    lista_beneficios: [
      "115 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: no tiene",
    ],
  },
  {
    origen_id: 51,
    origen_nombre: "ENTEL CHIP 94.80 PLUS",
    lista_beneficios: [
      "16 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 1 GB",
    ],
  },
  {
    origen_id: 52,
    origen_nombre: "ENTEL CHIP 94.90",
    lista_beneficios: [
      "125 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 4 GB",
    ],
  },
  {
    origen_id: 53,
    origen_nombre: "ENTEL POWER 94.90",
    lista_beneficios: ["Ilimitado con 125 GB en AV", "Roaming: 4 GB"],
  },
  {
    origen_id: 54,
    origen_nombre: "ENTEL POWER 94.90 B",
    lista_beneficios: ["Ilimitado con 125 GB en AV", "Roaming: 4 GB"],
  },
  {
    origen_id: 55,
    origen_nombre: "ENTEL POWER 99.90 SD",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 5 GB"],
  },
  {
    origen_id: 56,
    origen_nombre: "ENTEL CHIP 104.80 PLUS",
    lista_beneficios: [
      "17 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 1 GB",
    ],
  },
  {
    origen_id: 57,
    origen_nombre: "ENTEL CHIP 109.90 PLUS",
    lista_beneficios: [
      "18 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 3 GB",
    ],
  },
  {
    origen_id: 58,
    origen_nombre: "ENTEL POWER 109.90",
    lista_beneficios: ["Ilimitado con 140 GB en AV", "Roaming: 5.5 GB"],
  },
  {
    origen_id: 59,
    origen_nombre: "NEGOCIO CHIP R 109.90",
    lista_beneficios: ["31 GB en AV", "Roaming: 3 GB"],
  },
  {
    origen_id: 60,
    origen_nombre: "ENTEL CHIP 114.80",
    lista_beneficios: [
      "20 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 3 GB",
    ],
  },
  {
    origen_id: 61,
    origen_nombre: "ENTEL CHIP 119.90",
    lista_beneficios: [
      "8 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 1 GB",
    ],
  },
  {
    origen_id: 62,
    origen_nombre: "ENTEL CHIP 129.90 PLUS",
    lista_beneficios: [
      "25 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 5 GB",
    ],
  },
  {
    origen_id: 63,
    origen_nombre: "ENTEL POWER 129.90",
    lista_beneficios: ["Ilimitado con 150 GB en AV", "Roaming: 8 GB"],
  },
  {
    origen_id: 64,
    origen_nombre: "ENTEL POWER 129.90 A",
    lista_beneficios: ["Ilimitado con 150 GB en AV", "Roaming: 8 GB"],
  },
  {
    origen_id: 65,
    origen_nombre: "ENTEL CHIP 145.90",
    lista_beneficios: [
      "12 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 3 GB",
    ],
  },
  {
    origen_id: 66,
    origen_nombre: "ENTEL CONTROL 149.90",
    lista_beneficios: [
      "25 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 1 GB",
    ],
  },
  {
    origen_id: 67,
    origen_nombre: "ENTEL LIBRE 149.90",
    lista_beneficios: [
      "25 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 1 GB",
    ],
  },
  {
    origen_id: 68,
    origen_nombre: "ENTEL CHIP 155.90",
    lista_beneficios: [
      "14 GB en AV",
      "Whatsapp, Waze, Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
      "Roaming: 3 GB",
    ],
  },
  {
    origen_id: 69,
    origen_nombre: "NEGOCIO POWER R 156.40",
    lista_beneficios: ["46 GB en AV", "Roaming: no tiene"],
  },
  {
    origen_id: 70,
    origen_nombre: "ENTEL CHIP 159.90 PLUS",
    lista_beneficios: ["Ilimitado con 160 GB en AV", "Roaming: 12 GB"],
  },
  {
    origen_id: 71,
    origen_nombre: "ENTEL POWER 159.90 5G",
    lista_beneficios: ["Ilimitado con 45 GB en AV", "Roaming: 7 GB"],
  },
  {
    origen_id: 72,
    origen_nombre: "ENTEL CHIP 199.90",
    lista_beneficios: ["Ilimitado con 170 GB en AV", "Roaming: 16 GB"],
  },
  {
    origen_id: 73,
    origen_nombre: "ENTEL CHIP 199.90 LIBRE",
    lista_beneficios: ["Ilimitado con 170 GB en AV", "Roaming: 16 GB"],
  },
];

export const lista_opcion = [
  {
    origen_id: 1,
    opcion_id: 1,
    plan_nombre: "null",
    lista_beneficios: null,
    lista_resumen: null,
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 1,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 2,
    opcion_id: 1,
    plan_nombre: "null",
    lista_beneficios: null,
    lista_resumen: null,
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 2,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 3,
    opcion_id: 1,
    plan_nombre: "null",
    lista_beneficios: null,
    lista_resumen: null,
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 3,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 4,
    opcion_id: 1,
    plan_nombre: "null",
    lista_beneficios: null,
    lista_resumen: null,
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 4,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 5,
    opcion_id: 1,
    plan_nombre: "null",
    lista_beneficios: null,
    lista_resumen: null,
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 5,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 6,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Chip 25.90</font>",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["No pierde GB"],
    ahorro_anual: 24,
    permite_downselling: true,
  },
  {
    origen_id: 6,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 7,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Chip 25.90</font>",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["No pierde GB"],
    ahorro_anual: 24,
    permite_downselling: true,
  },
  {
    origen_id: 7,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 8,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Chip 25.90</font>",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["No pierde GB"],
    ahorro_anual: 24,
    permite_downselling: true,
  },
  {
    origen_id: 8,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 9,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Chip 25.90</font>",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 1 GB"],
    ahorro_anual: 36,
    permite_downselling: true,
  },
  {
    origen_id: 9,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 10,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Chip 25.90</font>",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 1 GB"],
    ahorro_anual: 36,
    permite_downselling: true,
  },
  {
    origen_id: 10,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 11,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Chip 25.90</font>",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 1 GB"],
    ahorro_anual: 36,
    permite_downselling: true,
  },
  {
    origen_id: 11,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 12,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Chip 25.90</font>",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 1 GB"],
    ahorro_anual: 36,
    permite_downselling: true,
  },
  {
    origen_id: 12,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 13,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Chip 25.90</font>",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde 5 GB"],
    ahorro_anual: 60,
    permite_downselling: true,
  },
  {
    origen_id: 13,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 14,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Chip 25.90</font>",
    lista_beneficios: [
      "10 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde 5 GB"],
    ahorro_anual: 60,
    permite_downselling: true,
  },
  {
    origen_id: 14,
    opcion_id: 2,
    plan_nombre: "null",
    ahorro_anual: null,
    permite_downselling: false,
  },
  {
    origen_id: 15,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    lista_beneficios: [
      "14 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde 6 GB"],
    ahorro_anual: 60,
    permite_downselling: true,
  },
  {
    origen_id: 15,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip 25.90</font>",
    ahorro_anual: 120,
    permite_downselling: true,
  },
  {
    origen_id: 16,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    lista_beneficios: [
      "14 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde 6 GB"],
    ahorro_anual: 84,
    permite_downselling: true,
  },
  {
    origen_id: 16,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip 25.90</font>",
    ahorro_anual: 144,
    permite_downselling: true,
  },
  {
    origen_id: 17,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    lista_beneficios: [
      "14 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde 6 GB"],
    ahorro_anual: 84,
    permite_downselling: true,
  },
  {
    origen_id: 17,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip 25.90</font>",
    ahorro_anual: 144,
    permite_downselling: true,
  },
  {
    origen_id: 18,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    lista_beneficios: [
      "14 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Gana 1 GB en AV",
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
    ],
    ahorro_anual: 108,
    permite_downselling: true,
  },
  {
    origen_id: 18,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP 27.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip 25.90</font>",
    ahorro_anual: 168,
    permite_downselling: true,
  },
  {
    origen_id: 19,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 6 GB"],
    ahorro_anual: 7,
    permite_downselling: true,
  },
  {
    origen_id: 19,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 127,
    permite_downselling: true,
  },
  {
    origen_id: 20,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 6 GB"],
    ahorro_anual: 7,
    permite_downselling: true,
  },
  {
    origen_id: 20,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 127,
    permite_downselling: true,
  },
  {
    origen_id: 21,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 6 GB"],
    ahorro_anual: 7,
    permite_downselling: true,
  },
  {
    origen_id: 21,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 127,
    permite_downselling: true,
  },
  {
    origen_id: 22,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 4 GB"],
    ahorro_anual: 36,
    permite_downselling: true,
  },
  {
    origen_id: 22,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 156,
    permite_downselling: true,
  },
  {
    origen_id: 23,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 2 GB"],
    ahorro_anual: 72,
    permite_downselling: true,
  },
  {
    origen_id: 23,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 192,
    permite_downselling: true,
  },
  {
    origen_id: 24,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 1 GB"],
    ahorro_anual: 84,
    permite_downselling: true,
  },
  {
    origen_id: 24,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 204,
    permite_downselling: true,
  },
  {
    origen_id: 25,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 1 GB"],
    ahorro_anual: 84,
    permite_downselling: true,
  },
  {
    origen_id: 25,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 204,
    permite_downselling: true,
  },
  {
    origen_id: 26,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 20 GB"],
    ahorro_anual: 84,
    permite_downselling: true,
  },
  {
    origen_id: 26,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 204,
    permite_downselling: true,
  },
  {
    origen_id: 27,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Gana 20 GB"],
    ahorro_anual: 84,
    permite_downselling: true,
  },
  {
    origen_id: 27,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 204,
    permite_downselling: true,
  },
  {
    origen_id: 28,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Gana 25 GB",
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Pierde Ilimitado",
    ],
    ahorro_anual: 84,
    permite_downselling: true,
  },
  {
    origen_id: 28,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 204,
    permite_downselling: true,
  },
  {
    origen_id: 29,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde 1 GB"],
    ahorro_anual: 84,
    permite_downselling: true,
  },
  {
    origen_id: 29,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 204,
    permite_downselling: true,
  },
  {
    origen_id: 30,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde 16 GB",
      "Pierde Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
      "Pierde Roaming",
    ],
    ahorro_anual: 156,
    permite_downselling: true,
  },
  {
    origen_id: 30,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 276,
    permite_downselling: true,
  },
  {
    origen_id: 31,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde 16 GB"],
    ahorro_anual: 156,
    permite_downselling: true,
  },
  {
    origen_id: 31,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 276,
    permite_downselling: true,
  },
  {
    origen_id: 32,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde 16 GB"],
    ahorro_anual: 156,
    permite_downselling: true,
  },
  {
    origen_id: 32,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 276,
    permite_downselling: true,
  },
  {
    origen_id: 33,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde 41 GB",
      "Pierde Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
      "Pierde 3 GB Roaming",
    ],
    ahorro_anual: 204,
    permite_downselling: true,
  },
  {
    origen_id: 33,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 324,
    permite_downselling: true,
  },
  {
    origen_id: 34,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde 16 GB", "Gana RRSS Ilimitadas"],
    ahorro_anual: 204,
    permite_downselling: true,
  },
  {
    origen_id: 34,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 324,
    permite_downselling: true,
  },
  {
    origen_id: 35,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde 51 GB",
      "Pierde Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
    ],
    ahorro_anual: 276,
    permite_downselling: true,
  },
  {
    origen_id: 35,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 396,
    permite_downselling: true,
  },
  {
    origen_id: 36,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde 51 GB",
      "Pierde Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
    ],
    ahorro_anual: 276,
    permite_downselling: true,
  },
  {
    origen_id: 36,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 396,
    permite_downselling: true,
  },
  {
    origen_id: 37,
    opcion_id: 1,
    plan_nombre: "<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Gana 18 GB",
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Pierde Ilimitado",
    ],
    ahorro_anual: 276,
    permite_downselling: true,
  },
  {
    origen_id: 37,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 396,
    permite_downselling: true,
  },
  {
    origen_id: 38,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Gana 18 GB",
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Pierde Ilimitado",
    ],
    ahorro_anual: 276,
    permite_downselling: true,
  },
  {
    origen_id: 38,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 396,
    permite_downselling: true,
  },
  {
    origen_id: 39,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Gana 18 GB",
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Pierde Ilimitado",
    ],
    ahorro_anual: 276,
    permite_downselling: true,
  },
  {
    origen_id: 39,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 396,
    permite_downselling: true,
  },
  {
    origen_id: 40,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Gana 16 GB",
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
    ],
    ahorro_anual: 276,
    permite_downselling: true,
  },
  {
    origen_id: 40,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 396,
    permite_downselling: true,
  },
  {
    origen_id: 41,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde Ilimitado y 8 GB en AV",
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Full",
    ],
    ahorro_anual: 324,
    permite_downselling: true,
  },
  {
    origen_id: 41,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 444,
    permite_downselling: true,
  },
  {
    origen_id: 42,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde 86 GB",
      "Pierde Spotify y Apple Music Ilimitado; Facebook e Instagram Full",
      "Pierde 3.5 GB Roaming",
    ],
    ahorro_anual: 384,
    permite_downselling: true,
  },
  {
    origen_id: 42,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 504,
    permite_downselling: true,
  },
  {
    origen_id: 43,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde 66 GB",
      "Pierde Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
    ],
    ahorro_anual: 384,
    permite_downselling: true,
  },
  {
    origen_id: 43,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 504,
    permite_downselling: true,
  },
  {
    origen_id: 44,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Pierde Ilimitado y 66 GB en AV",
    ],
    ahorro_anual: 384,
    permite_downselling: true,
  },
  {
    origen_id: 44,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 504,
    permite_downselling: true,
  },
  {
    origen_id: 45,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde 66 GB en AV",
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
    ],
    ahorro_anual: 384,
    permite_downselling: true,
  },
  {
    origen_id: 45,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 504,
    permite_downselling: true,
  },
  {
    origen_id: 46,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Gana Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
    ],
    ahorro_anual: 503,
    permite_downselling: true,
  },
  {
    origen_id: 46,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 623,
    permite_downselling: true,
  },
  {
    origen_id: 47,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde 76 GB",
      "Pierde Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
    ],
    ahorro_anual: 504,
    permite_downselling: true,
  },
  {
    origen_id: 47,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 624,
    permite_downselling: true,
  },
  {
    origen_id: 48,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Gana 25 GB",
      "Pierde Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
    ],
    ahorro_anual: 504,
    permite_downselling: true,
  },
  {
    origen_id: 48,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 624,
    permite_downselling: true,
  },
  {
    origen_id: 49,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: ["Pierde Ilimitado sin Fair Use en AV", "Pierde roaming"],
    ahorro_anual: 564,
    permite_downselling: true,
  },
  {
    origen_id: 49,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 684,
    permite_downselling: true,
  },
  {
    origen_id: 50,
    opcion_id: 1,
    plan_nombre: "ENTEL CHIP+ 42.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 39.90</font>",
    lista_beneficios: [
      "34 GB en AV",
      "Whatsapp y Waze Ilimitado; Facebook e Instagram Fotos",
      "Roaming: no tiene",
    ],
    lista_resumen: [
      "Pierde 81 GB",
      "Pierde Spotify, Apple Music y SoundCloud Ilimitado; Facebook e Instagram Full",
    ],
    ahorro_anual: 564,
    permite_downselling: true,
  },
  {
    origen_id: 50,
    opcion_id: 2,
    plan_nombre: "ENTEL CHIP+ 32.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel chip+ 29.90</font>",
    ahorro_anual: 684,
    permite_downselling: true,
  },
  {
    origen_id: 51,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    lista_beneficios: ["130 GB en AV", "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana 114 GB", "Gana 2.5 GB Roaming"],
    ahorro_anual: 179,
    permite_downselling: true,
  },
  {
    origen_id: 51,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER CHIP 66.90",
    ahorro_anual: 335,
    permite_downselling: true,
  },
  {
    origen_id: 52,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    lista_beneficios: ["130 GB en AV", "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana 5 GB", "Pierde 0.5 GB Roaming"],
    ahorro_anual: 180,
    permite_downselling: true,
  },
  {
    origen_id: 52,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER CHIP 66.90",
    ahorro_anual: 336,
    permite_downselling: true,
  },
  {
    origen_id: 53,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    lista_beneficios: ["130 GB en AV", "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana 5 GB", "Pierde Ilimitado"],
    ahorro_anual: 180,
    permite_downselling: true,
  },
  {
    origen_id: 53,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER CHIP 66.90",
    ahorro_anual: 336,
    permite_downselling: true,
  },
  {
    origen_id: 54,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    lista_beneficios: ["130 GB en AV", "Whatsapp, Waze, Spotify y Apple Music Ilimitado; Facebook e Instagram Full", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana 5 GB", "Pierde Ilimitado"],
    ahorro_anual: 180,
    permite_downselling: true,
  },
  {
    origen_id: 54,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER CHIP 66.90",
    ahorro_anual: 336,
    permite_downselling: true,
  },
  {
    origen_id: 55,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Pierde 1.5 GB Roaming"],
    ahorro_anual: 60,
    permite_downselling: true,
  },
  {
    origen_id: 55,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 240,
    permite_downselling: true,
  },
  {
    origen_id: 56,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 2.5 GB Roaming"],
    ahorro_anual: 119,
    permite_downselling: true,
  },
  {
    origen_id: 56,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 299,
    permite_downselling: true,
  },
  {
    origen_id: 57,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 0.5 GB Roaming"],
    ahorro_anual: 180,
    permite_downselling: true,
  },
  {
    origen_id: 57,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 360,
    permite_downselling: true,
  },
  {
    origen_id: 58,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Pierde 2 GB Roaming"],
    ahorro_anual: 180,
    permite_downselling: true,
  },
  {
    origen_id: 58,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 360,
    permite_downselling: true,
  },
  {
    origen_id: 59,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 0.5 GB Roaming"],
    ahorro_anual: 180,
    permite_downselling: true,
  },
  {
    origen_id: 59,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 360,
    permite_downselling: true,
  },
  {
    origen_id: 60,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 0.5 GB Roaming"],
    ahorro_anual: 239,
    permite_downselling: true,
  },
  {
    origen_id: 60,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 419,
    permite_downselling: true,
  },
  {
    origen_id: 61,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 2.5 GB Roaming"],
    ahorro_anual: 300,
    permite_downselling: true,
  },
  {
    origen_id: 61,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 480,
    permite_downselling: true,
  },
  {
    origen_id: 62,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Pierde 1.5 GB Roaming"],
    ahorro_anual: 420,
    permite_downselling: true,
  },
  {
    origen_id: 62,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 600,
    permite_downselling: true,
  },
  {
    origen_id: 63,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Pierde 4.5 GB Roaming"],
    ahorro_anual: 420,
    permite_downselling: true,
  },
  {
    origen_id: 63,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 600,
    permite_downselling: true,
  },
  {
    origen_id: 64,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Pierde 4.5 GB Roaming"],
    ahorro_anual: 420,
    permite_downselling: true,
  },
  {
    origen_id: 64,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 600,
    permite_downselling: true,
  },
  {
    origen_id: 65,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 0.5 GB Roaming"],
    ahorro_anual: 612,
    permite_downselling: true,
  },
  {
    origen_id: 65,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 792,
    permite_downselling: true,
  },
  {
    origen_id: 66,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 2.5 GB Roaming"],
    ahorro_anual: 660,
    permite_downselling: true,
  },
  {
    origen_id: 66,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 840,
    permite_downselling: true,
  },
  {
    origen_id: 67,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 2.5 GB Roaming"],
    ahorro_anual: 660,
    permite_downselling: true,
  },
  {
    origen_id: 67,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 840,
    permite_downselling: true,
  },
  {
    origen_id: 68,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 0.5 GB Roaming"],
    ahorro_anual: 732,
    permite_downselling: true,
  },
  {
    origen_id: 68,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 912,
    permite_downselling: true,
  },
  {
    origen_id: 69,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Gana 3.5 GB Roaming"],
    ahorro_anual: 738,
    permite_downselling: true,
  },
  {
    origen_id: 69,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 918,
    permite_downselling: true,
  },
  {
    origen_id: 70,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Pierde 8.5 GB Roaming"],
    ahorro_anual: 780,
    permite_downselling: true,
  },
  {
    origen_id: 70,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 960,
    permite_downselling: true,
  },
  {
    origen_id: 71,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Pierde 3.5 GB Roaming"],
    ahorro_anual: 780,
    permite_downselling: true,
  },
  {
    origen_id: 71,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 960,
    permite_downselling: true,
  },
  {
    origen_id: 72,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Pierde 12.5 GB Roaming"],
    ahorro_anual: 1260,
    permite_downselling: true,
  },
  {
    origen_id: 72,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 1440,
    permite_downselling: true,
  },
  {
    origen_id: 73,
    opcion_id: 1,
    plan_nombre: "ENTEL POWER 94.90 SD<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel power 89.90 SD</font>",
    lista_beneficios: ["Ilimitado en AV", "Roaming: 3.5 GB"],
    lista_resumen: ["Gana Ilimitado en AV", "Pierde 12.5 GB Roaming"],
    ahorro_anual: 1260,
    permite_downselling: true,
  },
  {
    origen_id: 73,
    opcion_id: 2,
    plan_nombre: "ENTEL POWER+ 79.90<br><br><font color='red' size='3'>*Importante: El plan se visualizará en OC como Entel Power+ 74.90</font>",
    ahorro_anual: 1440,
    permite_downselling: true,
  },
];